//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.Models
{
    using System.Collections.Generic;
    
    public partial class Auditorium
    {
        public Auditorium()
        {
            this.Reservations = new HashSet<Reservation>();
            this.AdditionalEquipments = new HashSet<AdditionalEquipment>();
        }
    
        public int AuditoriumId { get; set; }
        public string AuditoriumName { get; set; }
        public short Capacity { get; set; }
        public int AuditoriumEquipment { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<AdditionalEquipment> AdditionalEquipments { get; set; }
    }
}
