//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse.Models
{  
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int Auditorium { get; set; }
        public string Purpose { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int CreatedBy { get; set; }
        public bool Type { get; set; }
    
        public virtual Auditorium Auditoriums { get; set; }
        public virtual User User { get; set; }
    }
}
